author: Михаил Воробьев
name: Студия Евгения Лепёхина
url: https://dontliem1.github.io
ig: https://instagram.com/lepekhinart
tg: https://tme.to/lepekhinart
vk: https://vk.com/lepekhinart
policy: https://docs.google.com/document/d/1pVJAbN8KmAKf5PvjB85avqBVZGQ_yq1aMDNdjJ66eUo/edit?usp=sharing
email: mailbox@lepekhin.art
tel: +7 919 959-80-65
