ig: https://instagram.com/lepekhinart
tg: https://tme.to/lepekhinart
vk: https://vk.com/lepekhinart
email: mailbox@lepekhin.art
tel: +7 919 959-80-65
address: Тюмень, ул. Водопроводная, 34 офис 412
address_label: офис студии принимает гостей с 11:00 до 19:00 по местному времени
address_url: https://yandex.ru/maps/-/CCQlZFrVGC
author: Михаил Воробьев
name: Студия Евгения Лепёхина
url: https://dontliem1.github.io
policy: https://docs.google.com/document/d/1pVJAbN8KmAKf5PvjB85avqBVZGQ_yq1aMDNdjJ66eUo/edit?usp=sharing
email_label: на письма отвечают Валерия и Евгений
tel_label: звонки принимает Валерия, менеджер студии
