backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
logo_url: "https://lepekhinart.netlify.app/static/img/lepekhin.svg"
locale: "ru"
site_url: https://lepekhinart.netlify.app

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Портфолио"
    label_singular: 'проект'
    name: "portfolio"
    folder: "src/projects"
    create: true
    view_filters:
      - label: 'Черновики'
        field: draft
        pattern: true
      - label: 'Экспресс-проекты'
        field: express
        pattern: true
      - label: 'Проекты с кейсами'
        field: url
        pattern: 'http'
    editor:
      preview: false
    identifier_field: 'path'
    fields:
      - { label: 'Черновик', name: 'draft', widget: 'boolean', default: true }
      - { label: "Идентификатор проекта", name: "path", widget: "string", required: false, hint: 'Будет отображаться в адресной строке браузера после https://lepekhin.art/projects/.' }
      - { label: "Заголовок в портфолио", name: "title", widget: "string" }
      - { label: "Экспресс-проект", name: "express", widget: "boolean", required: false }
      - { label: "Широкая плашка", name: "wide", widget: "boolean", required: false }
      - { label: "Обложка для портфолио", name: "cover", widget: "image", media_folder: "covers", allow_multiple: false, hint: "646х990 пикселей для узких плашек, 1350х990 для широких." }
      - { label: "Ссылка на готовый проект", name: "url", widget: "string", required: false, hint: "Если установлено, из портфолио идёт переход сразу по ссылке, а не на страницу кейса." }
      - { label: 'Черновик', name: 'draft', widget: 'boolean', default: true }
      - { label: "Обложка страницы кейса для соцсетей", name: "og", widget: "image", media_folder: "og", allow_multiple: false, hint: "1200x630 пикселей", required: false }
      - label: 'Внутренние страницы'
        name: 'pages'
        widget: 'list'
        hint: 'Если больше одной, отображается переключатель'
        fields:
          - { label: "Подпись в переключателе", name: "label", widget: "string", hint: "Например, «Сайт 1.0»." }
          - { label: "Заголовок страницы", name: "heading", widget: "string" }
          - label: 'Вкладки'
            name: 'tabs'
            widget: 'list'
            hint: 'Если больше одной, отображается переключатель'
            fields:
              - { label: "Подпись в переключателе", name: "label", widget: "string", hint: "Например, «Результат» или «Описание»." }
              - {
                  label: 'Цветовая схема',
                  name: 'theme',
                  widget: 'select',
                  options: ['Стандартная', 'Чёрная', 'Мы предприниматели']
                    - { label: "Стандартная", value: "default" }
                    - { label: "Чёрная", value: "black" }
                    - { label: "Мы предприниматели", value: "enter" }
                }
              - label: 'Содержимое вкладки'
                name: 'body_list'
                widget: 'list'
                types:
                  - label: 'Втупительная секция'
                    name: 'beginning'
                    widget: 'object'
                    fields:
                      - { label: 'Вступление', name: 'text', widget: 'text' }
                      - { label: 'Ссылка на готовый проект', name: 'link', widget: 'string', required: false, hint: 'Например, prize.we-enter.ru' }
                      - { label: 'Полный URL', name: 'url', widget: 'string', required: false, hint: 'Например, https://prize.we-enter.ru/' }
                      - { label: 'Подпись', name: 'label', widget: 'string', required: false, hint: 'Например, «сайт наполняется заказчиком»' }
              - { label: "Гарнитура", name: "font", widget: "string", required: false }
              - { label: "Дата выпуска", name: "date", widget: "datetime", time_format: false, required: false }
              - { label: "За сколько дней сделано", name: "days", widget: "number", required: false }
  - label: "Блог"
    label_singular: 'пост'
    description: "Студийный блог"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "string" }
      - { label: "Автор", name: "author", widget: "string" }
      - { label: "Время публикации", name: "date", widget: "datetime" }
      - { label: "Содержимое", name: "body", widget: "markdown" }
      - widget: select
        label: "Теги"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Настройка"
    name: "settings"
    sortable_fields: []
    editor:
      preview: false
    files:
      - label: "Навигация"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Ссылки"
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: "Подпись", name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Список проектов"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: "Карточки проектов"
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: "Заголовок", name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: "Описание", name: desc, widget: string }
      - label: "Команда"
        label_singular: "сотрудник"
        name: team
        file: "src/_data/team.yaml"
        fields:
          - label: "Сотрудники"
            label_singular: "сотрудник"
            name: teammates
            widget: list
            collapsed: false
            fields:
              - { label: "Подпись", name: title, widget: string }
              - { label: "Фото", name: img, widget: image, allow_multiple: false }
      - label: "Контактная информация"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Название организации", name: name, widget: string }
          - { label: "Ссылка на Инстаграм", name: ig, widget: string }
          - { label: "Ссылка на Телеграм", name: tg, widget: string }
          - { label: "Ссылка на ВКонтакте", name: vk, widget: string }
          - { label: "Ссылка на политику конфиденциальности", name: policy, widget: string }
          - { label: "Электронная почта", name: email, widget: string }
          - { label: "Подпись к почте", name: email_label, widget: string }
          - { label: "Телефон", name: tel, widget: string, hint: "Формат: +7 999 999-99-99" }
          - { label: "Подпись к телефону", name: tel_label, widget: string }
          - { label: "Адрес", name: address, widget: string }
          - { label: "Подпись к адресу", name: address_label, widget: string }
          - { label: "Ссылка на карту", name: address_url, widget: string }
