backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
logo_url: "https://lepekhinart.netlify.app/static/img/lepekhin.svg"
locale: "ru"
site_url: https://lepekhinart.netlify.app

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Блог"
    description: "Студийный блог"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "string" }
      - { label: "Автор", name: "author", widget: "string" }
      - { label: "Время публикации", name: "date", widget: "datetime" }
      - { label: "Содержимое", name: "body", widget: "markdown" }
      - widget: select
        label: "Теги"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Настройка"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Навигация"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Ссылки"
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: "Подпись", name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Список проектов"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: "Карточки проектов"
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: "Заголовок", name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: "Описание", name: desc, widget: string }
      - label: "Команда"
        name: team
        file: "src/_data/team.yaml"
        fields:
          - label: "Сотрудники"
            name: teammates
            widget: list
            collapsed: false
            fields:
              - { label: "Фото", name: img, widget: image, allow_multiple: false }
              - { label: "Подпись", name: title, widget: string }
      - label: "Контактная информация"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Название организации", name: name, widget: string }
          - { label: "Ссылка на Инстаграм", name: ig, widget: string }
          - { label: "Ссылка на Телеграм", name: tg, widget: string }
          - { label: "Ссылка на ВКонтакте", name: vk, widget: string }
          - { label: "Ссылка на политику конфиденциальности", name: policy, widget: string }
          - { label: "Электронная почта", name: email, widget: string }
          - { label: "Подпись к почте", name: email_label, widget: string }
          - { label: "Телефон", name: tel, widget: string, hint: "Формат: +7 999 999-99-99" }
          - { label: "Подпись к телефону", name: tel_label, widget: string }
          - { label: "Адрес", name: address, widget: string }
          - { label: "Подпись к адресу", name: address_label, widget: string }
          - { label: "Ссылка на карту", name: address_url, widget: string }
